usr/lib/*/*.so.*
usr/lib/ruby/ignition/cmdgazebo[0-99].rb
usr/lib/ruby/ignition/cmdmodel[0-99].rb
usr/share/ignition/ignition-gazebo[0-99]/*.config
usr/share/ignition/ignition-gazebo[0-99]/gui/*
usr/share/ignition/ignition-gazebo[0-99]/worlds/*
usr/share/ignition/gazebo[0-99].yaml
usr/share/ignition/model[0-99].yaml
usr/share/gz/*
obj-*/ignition-gazebo[0-99].svg usr/share/icons/hicolor/scalable/apps/
obj-*/ignition-gazebo[0-99].desktop usr/share/applications/
